### ISSUE TITLE
exceções estão "estourando" para o usuário

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#1]
**Problema**
Quando ocorre um erro inesperado, ou exceção, o erro é exibido para o usuário sem o devido tratamento.

**Como reproduzir**
- Edite o arquivo `config.php` comentando a porta do banco. Isso causará um `Fatal error` por não conseguir conectar ao banco

**Possível solução**
Utilizar um try/catch na tentativa de conexão e exibir um erro amigável para o usuário, sem expor detalhes da infraestrutura

**Possui print?**
![image](https://github.com/luizfspintoo/note-sync/assets/13575331/cc696eee-efe0-4b67-9ef2-f5a6ed9fe6cc)

**Comment by luizfspintoo** [comment]
#### Erro de Conexão com o Banco de Dados:
- Adicionei um bloco try/catch na classe Database.
- Se as configurações do banco de dados estiverem corretas, o fluxo continua normalmente.
- Caso contrário, uma página de erro 500 é exibida, tornando a experiência mais amigável.
#### Centralização das Configurações:
- Coloquei o username e password que estava na classe Database no arquivo config.php.
- Isso centraliza todas as configurações do banco de dados em um único arquivo.

![image](https://github.com/luizfspintoo/note-sync/assets/122656846/702ca7b6-2f52-4117-a5d3-165a55ccc422)

**Comment by npsouza** [comment]
**Experiência do Usuário (UX)**
Isso já melhora um pouco a experiência do usuário, inclusive gostei da opção de falar com o suporte, mas ainda não é o ideal. O usuário foi impedido de navegar no restante do sistema e será redirecionado para outra página que pode ser bem diferente da que ele está usando no momento.

Nem todas as features dependem do banco de dados o tempo todo e da mesma forma. O código "500" e "banco de dados" são termos técnicos que podem não fazer sentido para o usuário. O ideal aqui é exibir uma mensagem dentro do contexto na qual o usuário está utilizando. Por exemplo: se o problema ocorrer durante o cadastro do usuário, deveria exibir uma mensagem na mesma tela falando algo como "Desculpe! Não foi possível concluir o cadastro no momento, tente novamente ou entre em contato com o suporte". Essa mensagem pode servir para qualquer erro "desconhecido" nesse fluxo. 

Entendo pode não ser um trabalho simples, mas é necessário revisar os fluxo e ver se tem possibilidades de ocorrer esse tipo de erro, se tem try/catch e o que faz no catch.

![image](https://github.com/luizfspintoo/note-sync/assets/13575331/e1da6dd9-a8b0-4347-9b9f-c5058d85d4aa)

**Comment by npsouza** [comment]
**Code review**
https://github.com/luizfspintoo/note-sync/commit/5b28435f168d72fdffa781580e19819d46b03dc9#diff-505d09a0b498263dc2fd2711e136a30e50c3da034089d9c8040c23931e05778eR22-R23
É uma boa prática uma classe/método ter apenas uma responsabilidade bem clara e explícita. Nesse código aqui a classe Database, que conecta no banco, está assumindo a responsabilidade de renderizar uma a view e usando `exit()` que causa efeito colatareal (side effect).  

O ideal aqui talvez seja retornar uma exceção mais específica do erro, para o método ou operação que estiver consumindo tratar como preferir
```php
// Database.php
...
$dns = "mysql:" . http_build_query($config, "", ";");

try {
    $this->connection = new PDO($dns, $config["username"], $config["password"], [
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
    ]);
} catch (PDOException $error) {
    throw new ErrorException('ERROR_CONNECTION_DATABASE');
}

// consumidor da classe Database
try {
     return new Database($config);
 } catch (ErrorException $e) {
    if ($e->getMessage() == "ERROR_CONNECTION_DATABASE") {
         //faça algo aqui - redirect() - view()
    }
    throw $e; 
 }
```

https://github.com/luizfspintoo/note-sync/commit/5b28435f168d72fdffa781580e19819d46b03dc9#diff-27748a5a5acf614fc6444e3c5f85f8a62565341fc28f79cdcce1703d1e28017c
É uma boa prática todo arquivo html ter as tags html / head / body, inclusive seria importante herdar o cabeçalho existente, pois eventualmente pode ser necessário instalar um Google Analytics e essa página ficaria de fora.

**Comment by luizfspintoo** [comment]
Boa noite Nathan, tudo bem?

Realizei a implementação dos try/catch no fluxo restante da aplicação. Se quiser conferir e dar uma olhadinha, fique a vontade, se houver erros me avise por favor.
