### ISSUE TITLE
documentação não fala sobre configuração correta do banco

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#10]
A documentação contida no README fala sobre configurar um banco de dados MySQL, mas não fala como criar as tabelas e quais tabelas precisam ser criadas. Vi que tem o arquivo `myapp.sql`, vale citar ele e como usar ele.

**Comment by luizfspintoo** [comment]
Melhorei a forma como estava explicando a configuração do banco de dados, e quais as tabelas são usadas na aplicação.

**Comment by npsouza** [comment]
Melhorou, mas não seguiu a recomendação que deixei no ticket ali em cima 😅 
> Vi que tem o arquivo myapp.sql, vale citar ele e como usar ele.

Da forma como ficou o sql ficou duplicado, no `README.md` e no `myapp.sql`, no futuro, quando houver novas tabelas ou campos, precisa editar dois lugares. Corre o risco de ficar divergente. 

Acho que uma forma mais simples é instruir a copiar, ou executar, o `myapp.sql`. Assim o dev já pega atualizado sempre.

**Comment by luizfspintoo** [comment]
Modifiquei a escrita, apontando para o arquivo myapp.sql, assim fica mais fácil de realizar alterações futuras como você mencionou. Espero que esteja claro na descrição, caso não esteja me avise por favor.
