### ISSUE TITLE
falta de logs para monitoramento

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#12]
**Problema**
Falta de visibilidade sobre o correto funcionamento do sistema e seus eventos (uso, erros e exceções).  Hoje caso ocorra um erro é necessário reproduzir todo o processo para entender qual erro aconteceu.

**Possível solução**
Com um sistema de logs é possível ver os logs gerado de operação para entender o que exatamente ocorreu. Adicionar configuração básica de logs utilizando um pacote como o [Monolog](https://github.com/Seldaek/monolog), por exemplo.

**Referência**
- [O que são arquivos de log e sua importância?](https://aws.amazon.com/pt/what-is/log-files/#:~:text=Logs%20do%20sistema,erros%2C%20alertas%20e%20desligamentos%20inesperados.)

**Sugestão**
- [ ] Configurar composer no projeto(https://github.com/luizfspintoo/note-sync/issues/13)
- [ ] Configurar Monolog
- [ ] Mapear quais as principais operações da aplicação que precisam ser monitoradas (Login, Cadastro)
- [ ] Adicionar logs em etapas de sucesso e erro

**Comment by luizfspintoo** [comment]
Boa noite Nathan, já instalei a biblioteca Monolog e colotei o primeiro log já. Mas vou configurar em quais partes do projeto é mais necessário para coletar os logs.


![image](https://github.com/luizfspintoo/note-sync/assets/122656846/0fe453a5-bf2c-442b-8b37-07b046861472)

**Comment by npsouza** [comment]
Muito bom! Vou dar como resolvido, mas acho uma boa criar um container para isso, para não ficar fazendo `new Logger` em todo o lugar, parecido com o exemplo do banco de dados https://github.com/luizfspintoo/note-sync/blob/main/bootstrap.php

Deve dar pra usar ele mais ou menos assim
```php
App::resolve(Logger::class)->error('mensagem de erro')
```
