### ISSUE TITLE
configurar composer no projeto

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#13]
Para as próximas features vamos precisar instalar bibliotecas e para isso o ideal é instalar e configurar o composer no projeto.

**Sugestão**
Instalar o composer no pc seguindo as instruções [aqui](https://www.hostinger.com.br/tutoriais/como-instalar-e-usar-o-composer)

**Comment by luizfspintoo** [comment]
Composer instalado no projeto, e já configurado o autoload.

**Comment by npsouza** [comment]
Top, muito bom! Acho que vale atualizar a documentação agora e adicionar o `composer` como pré requisito e uma etapa para rodar o `composer install`

**Comment by luizfspintoo** [comment]
Claro muito bem lembrado, até porque se não rodar o composer não vai funcionar.
