### ISSUE TITLE
enviar feedback por email

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#14]
**Proposta**
Enviar a avaliação com o nome, email e feedback para o email pré-definido no sistema.

**Sugestão**
- [x] Configurar o composer (https://github.com/luizfspintoo/note-sync/issues/13)
- [x] Instalar a biblioteca [PHPMailer](https://github.com/PHPMailer/PHPMailer) no projeto
- [x] Baixar o HTML de um template de email [aqui](https://demo.react.email/preview/welcome/stripe-welcome)
- [x] (opcional) Criar uma conta no [mailtrap.io] para testar o recebimento do email(https://mailtrap.io/email-sandbox/)

**Comment by luizfspintoo** [comment]
Boa tarde Nathan, tudo bem?

Configuração e envio de email, funcionando.

![image](https://github.com/luizfspintoo/note-sync/assets/122656846/2d5a9c87-5b6a-45b4-9c0d-a2c8efa33952)

**Comment by luizfspintoo** [comment]
Só está com os caracteres quebrados, depois vou ver o que pode estar acontecendo pois está configurado para UTF-8

**Comment by npsouza** [comment]
Acho que vale mover as credenciais e o endereço de email que vai receber o email para o .env, dessa forma não fica expostas essas coisas e não precisamos editar o código na hora de publicar isso em produção.

Quando estiver resolvido a parte de UTF-8, me avisa que testo tudo aqui

**Comment by luizfspintoo** [comment]
Nesta etapa, consegui deixar as credencias na .env, e consumir na class Feedback, para envio do email.

A parte do UTF-8, não consegui resolver. 
- Tentei usar o <meta charset="UTF-8">, mas não funcionou
- Tentei usar o a função mb_convert_encoding(), também não funcionou.

O corpo do email, continua ainda com caracteres especiais.
Devo estar fazendo algo errado, pode me ajudar com isso?

**Comment by npsouza** [comment]
Claro, vejo sim. Está tudo comitado?

**Comment by luizfspintoo** [comment]
Boa noite Nathan, tudo bem?

Está sim comitado certinho.

**Comment by npsouza** [comment]
Pode copiar o log de erro e colar aqui por favor? (ou print)

**Comment by luizfspintoo** [comment]
Não consigo, tinha apagado os Logs kk.

Uma dúvida, de quanto em quanto tempo se apaga Logs, pois fica gigante dependendo do quanto tem, ou não se apaga ?

**Comment by npsouza** [comment]
Sobre os logs, acho que precisamos conversar 😅 tá um pouco estranho ter vários arquivos de logs, dá bastante trabalho para encontrar se teve erro e onde aconteceu. Sobre o tempo depende da aplicação e da necessidade do projeto, algumas ferramentas pagas guardam 15 dias no plano básico. Inclusive essa lib que está usando faz controle de rotação de logs [(`log rotate`)](https://en.wikipedia.org/wiki/Log_rotation), podemos configurar depois. Minha sugestão agora é não apagar nada, justamente para acostumar com busca em logs.

**Comment by npsouza** [comment]
Abri um PR resolvendo o bug e uma sugestão de refactor
https://github.com/luizfspintoo/note-sync/pull/22

Assim que ver o PR e aprovar a gente fecha essa issue aqui

**Comment by npsouza** [comment]
Pra não abrir outra issue, acho que vale atualizar o `myapp.sql` com as novas colunas da tabela feedback.

**Comment by luizfspintoo** [comment]
Certo, entendi sobre os logs. Tinha pensado em cada classe da aplicação no inicio, mas fica inviável até porque se tiver 100 classes, não faz sentido ter 100 arquivos de logs.

Sobre  a PR, eu vi e gostei bastante, já que não tinha pensado em usar o envio de e-mails em outras partes da aplicação, não só isso e até as configurações de charset ficou muito bom, valeu. Vou dar uma olhada com mais calma depois já que você colocou no container também.

**Comment by luizfspintoo** [comment]
Arquivo ```sql``` editado, conforme você mencionou, já adicionei as colunas.
