### ISSUE TITLE
criar Models e mover consultas sqls para elas

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#15]
Como a ideia do projeto é ser MVC, precisamos mover essas consultas sqls para uma classe e as outras devem apenas extender, ou herdar esse comportamento. Dessa forma mantemos o código de fácil manutenção e evolução, sem replicar código e sem expor consultas sql para todo o projeto.

**Comment by luizfspintoo** [comment]
Boa noite Nathan tudo bem?
Criei uma Model, chamada Model kk, mas tenho que mudar este nome. Ela recebe as consultas SQL como você tinha mencionado. Também criei uma classe, para receber os métodos padrão da classe Database, para a Database só ficar responsável por conectar-se ao banco.

**Comment by npsouza** [comment]
Opa, ficou bem legal, melhorou bastante. Acho que a classe model ainda está com muita responsabilidades, ela pode ficar um pouco melhor ainda. 

Aqui tem um exemplo de como pode utilizar [polimorfismo](https://medium.com/emanuelg-blog/programa%C3%A7%C3%A3o-orientada-a-objeto-em-php-polimorfismo-359ad60b947b) e [herança](https://medium.com/emanuelg-blog/programa%C3%A7%C3%A3o-orientada-a-objetos-em-php-heran%C3%A7a-parte-01-510ea1032b84) para criar models, e basicamente é o que Laravel faz também. Dá uma olhada e diz o que acha

https://github.com/luizfspintoo/note-sync/pull/17/files

**Comment by luizfspintoo** [comment]
Boa tarde Nathan, tudo bem?

Criei mais algumas Models, para separa a responsabilidade de deixar só com a class Model.
Agora tem a Model UsersModel, e FeedbackModel.
