### ISSUE TITLE
usar variáveis de ambiente

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#16]
Embora o arquivo `config.php` já ajuda muito a organizar o projeto, ele não é o tipo de arquivo ideal para manter credenciais do banco, pois para fazer o deploy teremos que editar esse arquivo e tomar cuidado de não comitar ele, pois senão ficarão expostas as credenciais. 

Para essa finalidade existem as variáveis de ambiente, são valores que podemos armazenar diretamente no servidor independente do repositório. Algumas hospedagem tem um painel para isso, outras permitem que faça o upload de um arquivo `.env` basta consumir ele pegar os valores. Outra vantagem é poder ter uma `.env` em cada ambiente,  local, teste e produção, sem editar o código fonte.

**Sugestão**
- [ ] Configurar o [composer](https://github.com/luizfspintoo/note-sync/issues/13)
- [ ] Instalar a [biblioteca que lê o arquivo .env](https://celke.com.br/artigo/como-usar-variaveis-de-ambiente-env-no-php)
- [ ] Alterar o `Database.php` para consumir os dados de conexão de um arquivo `.env`

**Comment by luizfspintoo** [comment]
Já criei o arquivo .env no projeto e configurei. Tem que dar uma olhadinha se ficou bom.
Até tinha me esquecido, eu cheguei a subir o arquivo, mas o ideal igual você disse ter um arquivo desse em cada ambiente, então nem subi ele.

**Comment by npsouza** [comment]
Mandou muito bem. Eu abri [esse PR](https://github.com/luizfspintoo/note-sync/pull/18) para sugerir um arquivo de exemplo, é uma boa prática em projetos que usem env, quase todos praticamente.
