### ISSUE TITLE
erro na página Conta

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#19]
**Problema**
Ao acessar a página Conta é exibida uma mensagem de erro não tratada. O email também não é preenchido como esperado.

**Como reproduzir**
- Criar uma nova conta
- Fazer login com a nova conta
- Acessar a página `Conta`

**Possui print?**
![image](https://github.com/luizfspintoo/note-sync/assets/13575331/63e6ef51-eab9-4643-b3df-432e6f718c90)

**Comment by luizfspintoo** [comment]
Nessa parte está mostrando normal na minha máquina 'a famosa frase né, aqui funciona normal kk', pois vou verificar e mandar um GIF. está com a versão mais nova?

**Comment by luizfspintoo** [comment]
Nathan, acredito que corrigi o bug, kk não estava recuperando o ultimo ID, então não criava a sessão corretamente para eu mostrar o email.

**Comment by luizfspintoo** [comment]
![image](https://github.com/luizfspintoo/note-sync/assets/122656846/a0648ce2-f9f6-44a3-8709-3767f57a1585)

**Comment by luizfspintoo** [comment]
![image](https://github.com/luizfspintoo/note-sync/assets/122656846/93bb58e5-543d-4a03-9df5-3cd09c513a34)

coloquei na função create
