### ISSUE TITLE
validação de senha no cadastro não funciona corretamente

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#2]
**Problema**
Não é possível concluir o cadastro de uma nova conta com uma senha de 10 caracteres. A partir de 10 caracteres o processo avança.

**Como reproduzir**
- Acessar a página de `Registre-se`
- Tentar criar uma nova conta informando uma senha de 10 caracteres
- Assim é possível ver a mensagem dizendo que a senha ainda é inválida

**Possível solução**
Verifica e ajustar o texto, ou a validação, pois devem estar divergindo.

**Possui print**
![image](https://github.com/luizfspintoo/note-sync/assets/13575331/36dccbf6-9b27-4788-9664-7c604c611ed3)

**Comment by luizfspintoo** [comment]
Foi ajustado conforme nossa ultima Call, tudo bem.
