### ISSUE TITLE
assim que o feedback dá erro o formulário fica limpo

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#20]
**Problemas**
- Assim que o feedback dá erro o formulário fica limpo
- O layout dos campos estão diferentes do resto do sistema
- As regras de preenchimento do formulário só aparecem depois de preenchidos

**Como reproduzir**
- Preencher os campos conforme necessário e deixar o campo de feedback com menos caracteres que o obrigatório.
- Clicar em `Avaliar Plataforma`
- Ver a mensagem de erro e observar que o campo nome e feedback foram limpos

**Possível solução**
## Melhoria de usabilidade
Informar ao usuário as regras e obrigatoriedade dos campos antes de preencher utilizando asteriscos ao lado do label do nome do campo e exibindo a quantidade mínima de caracteres logo abaixo do campo de feedback. Isso deve diminuir o volume de erros.

## Resolução do bug
O campo de feedback é um formulário muito importante para empresa, então se um usuário que investir seu tempo em preencher ele precisa ser o mais simples, fácil e seguro, por que senão ele vai abandonar isso. Apagar qualquer formulário em caso de erro, precisa ter um motivo muito sério pra isso, do contrário o usuário vai ficar bem frustado em ter que preencher de novo algo que talvez não tenha mais. O ideal aqui é sempre recuperar as informações que ele preencheu antes de enviar

## Ajustar o layout dos campos
É uma boa prática manter o padrão dos inputs de um sistema. Isso facilita com que o usuário continue usando todo o sistema e dá uma visão mais profissional do sistema.

**Possui print?**
![image](https://github.com/luizfspintoo/note-sync/assets/13575331/1b992bf6-bb64-4a1d-a1f9-6454844ab8c3)

**Comment by npsouza** [comment]
Outro ponto que notei aqui é o redirect quando conclui o envio do formulário, ficou bem estranho pois não dá a certeza de que o formulário foi enviado e tudo funcionou certinho

**Comment by luizfspintoo** [comment]
Correção do erros, usabilidade:
- Foi corrigido o erro de usabilidade, quando o usuário envia o formulário e algo der errado ele tem que preencher novamente, não vai ser mais necessário.
- Foi implementado os labels, e caracteres ao lado demonstrando que os campos são obrigatórios.
- Mudança no Layout, com os campos de input padrão como está em todo o sistema (ou muito próximo dos que estão).

**Comment by luizfspintoo** [comment]
Na parte do redirect, preciso implementar mensagens de sucesso, ou retorno dessas mensagens.

Na classe Feedback, mudei para redirecionar para a mesma página feedback, antes estava indo para dashboard.
É uma boa prática criar Sessão de respostas de sucesso, assim como foi criar a de erro se caso houver erro mostrar?

Porque no retorno da classe, não estou enviando nada para a controller, somente os valores antigos de input e erros, com a função old().


![image](https://github.com/luizfspintoo/note-sync/assets/122656846/5e83a213-fc89-42e1-93f3-4169447702bd)

**Comment by luizfspintoo** [comment]
![image](https://github.com/luizfspintoo/note-sync/assets/122656846/bbd82fd8-f91b-4c82-99e0-c8dde9f9dcc6)

**Comment by npsouza** [comment]
Ficou bem melhor! 

Um dica sobre o Github é usar os links dos arquivos em que quer citar, inclusive é possível selecionar as linhas que quer apontar. https://github.com/luizfspintoo/note-sync/blob/main/Core/Feedback.php#L112-L129
