### ISSUE TITLE
dúvida: tem algum motivo para só aceitarmos a porta 3306?

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#21]
(Fiquei curioso, isso não é uma pegadinha)

Tem algum motivo ou vantagem em limitar apenas para aceitar apenas a porta 3306? 
https://github.com/luizfspintoo/note-sync/blob/main/Core/Database.php#L41-L43

Pergunto isso porque estou usando um container e roteando para porta 8002 pois tenho outra aplicação usando a 3306

**Comment by luizfspintoo** [comment]
Não especifico, tinha colocado só para me gerar erro, de teste, tipo se a porta não tivesse preenchida.

Esqueci de tirar.

**Comment by npsouza** [comment]
Tranquilo, assim que remover fechamos essa issue aqui

**Comment by luizfspintoo** [comment]
Removido a condição do Database
