### ISSUE TITLE
não é possível concluir o cadastro de um novo usuário

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#3]
**Problema**
Não é possível concluir o cadastro de um novo usuário. A mensagem de erro também está bem ruim e pouco amigável para o usuário

**Como reproduzir**
- Acessar a página `Registre-se`
- Informa os dados corretamente
- Clicar em `Criar conta`

**Possíveis soluções**
- Adicionar try/catch nessa operação e exibir mensagens de erro melhores para o usuário
- Verificar/corrigir o uso do método `lastId`

**Possui print?**
![image](https://github.com/luizfspintoo/note-sync/assets/13575331/adc9212b-6c71-4fbf-a2ca-bed294c2d372)

**Comment by luizfspintoo** [comment]
Corrigido em nossa ultima Call, também.
