### ISSUE TITLE
algumas rotas estão acessíveis sem realizar o login

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#4]
**Problema**
A rota de criação de nota está acessível sem realizar o login, ou seja, sem existir sessão.

**Como reproduzir**
- Abrir o navegador em aba anônima
- E acessar a rota `/notes/create` pela barra de url do navegador

**Possível solução**
Revisitar as regras de redirecionamento dessa rota e também das outras

**Possui print?**
![image](https://github.com/luizfspintoo/note-sync/assets/13575331/9fc1478c-ffa9-4d66-948a-d745bbc91f39)

**Comment by luizfspintoo** [comment]
Ajustado, para que o usuário não consiga mais acessar rotas que precise de autenticação.
