### ISSUE TITLE
senha é exibida no campo de edição da conta

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#5]
**Problema**
A senha está exposta no campo senha na página `Informações da Conta`. 

**Como reproduzir**
- Clicar no avatar no topo direito
- Clicar em `Informação e Login`
- Ver o campo Senha com a senha atual criptografada

**Possível solução**
- Embora seja a senha criptografada, o ideal é nunca exibir esse tipo de informação. 
- Uma melhor opção é exibir um campo vazio de `Nova Senha`. Caso seja preenchido, a senha seja alterada no banco.
- É boa prática também em cadastro de senhas usar o campo `Confirmar Nova Senha`, isso mitiga problemas de cadastro de senhas equivocadas.

**Possui print**
![image](https://github.com/luizfspintoo/note-sync/assets/13575331/ddec498a-bcbc-44a9-b3f2-ec947862fde3)

**Comment by luizfspintoo** [comment]
Ajustado para que o campo senha, seja preenchido com uma nova senha assim como orientado. A questão da confirmação de senha, posso implementar na próxima versão.
