### ISSUE TITLE
erro após atualizar a conta

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#6]
**Problema**
Após alterar a senha da conta a página `Informações da Conta` mostra o formulário vazio e um erro logo acima

**Como reproduzir**
- Acessa a página `Informações da Conta`
- Altere a senha e clique em `Atualizar`
- Clique em sair do sistema e faça login novamente com a nova senha
- Acesse a página `Informações da Conta`
- Verá o formulário vazio e uma mensagem de `Warning`

**Possível solução**
- É necessário entender porque os dados não estão sendo carregados novamente e porque a mensagem de warning está sendo exibida.

**Possui print?**
![image](https://github.com/luizfspintoo/note-sync/assets/13575331/9bad47a0-6162-41d3-ac2f-7d06214134d3)

**Comment by luizfspintoo** [comment]
Problema corrigido, assim que o usuário atualizar a senha ele será redirecionado para o Dashboard. Sei que não é a melhor opção neste momento, mas só até eu implementar as mensagens de sucesso.

**Comment by npsouza** [comment]
Pelos testes que fiz aqui, agora não tem erro estourando, mas os dados ainda não estão sendo atualizados.

**Comment by luizfspintoo** [comment]
Boa noite Nathan, tudo bem?

Problema corrigido, pode testar por favor ? kk
