### ISSUE TITLE
erro ao salvar nova nota

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#7]
**Problema**
Erro ao salvar nova nota

**Como reproduzir**
- Clique em `Anotações` no menu lateral e visite a página de Anotações
- Clique em `Criar Anotação` 
- Insira uma anotação e clique em `Salvar`

**Possui print?**
![image](https://github.com/luizfspintoo/note-sync/assets/13575331/58544e23-beff-4036-b606-d5a18545a56a)

**Comment by luizfspintoo** [comment]
Problema corrigido, ao criar anotação. Está salvando normalmente.
