### ISSUE TITLE
não é possível selecionar as estrelas para enviar um feedback

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#8]
**Problema**
Ao clicar nas estrelas não alterar a avaliação do feedback. A única nota que é possível enviar é 3 estrelas

**Como reproduzir**
- Acessar a página `Feedback`
- Clicar em uma das estrelas e ver que nada acontece

**Possui print?**
![image](https://github.com/luizfspintoo/note-sync/assets/13575331/1f68080e-9740-4b16-8bf7-96caa375a657)

**Comment by luizfspintoo** [comment]
Foi conversado sobre o assunto na Call, achei melhor tirar neste momento para ficar minimalista. A mesma questão da funcionalidade de atualizar dados da conta, o usuário é redirecionado para 'Dashboard', até implementar as mensagens de sucesso.
