### ISSUE TITLE
feedback exibe erro quando tenta salvar

### ISSUE THREAD

**Issue by npsouza** [luizfspintoo/note-sync#9]
**Problema**
Ao tentar enviar o feedback ele exibe um erro

**Como reproduzir**
- Acessar a página `Feedback`
- Preencher com uma mensagem para feedback
- Clicar em `Avaliar Plataforma`
- Ver mensagem de erro

**Possível solução**
- A mensagem de erro indica que falta uma tabela, talvez falte atualizar o mysql do projeto e a documentação sobre isso
- Precisa existir tratamento nessa rotina para não estourar erros como esse para o usuário

**Possui print?**
![image](https://github.com/luizfspintoo/note-sync/assets/13575331/247705a4-c7b3-483f-8eae-0d8f37c2497c)

**Comment by luizfspintoo** [comment]
Problema corrigido, é possível salvar os feedbacks normalmente agora.
